baseurl         = ""
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Hugo Casper Two"
  subtitle    = "JourneyCode"

  cover       = "Uploads/Animals.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "priestlyharp"
  fbName = "james.lee.228"
  githubName = "JourneyCode"

  logo = "hugo-logo.png"
  orgName = ""
  orgWebsite = ""
  orgDescription = ""

  author = "JourneyCode"
  authorAvatar = "Uploads/Logo.jpg"
  authorLocation = "San Francisco, CA"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Teacher"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "caspertwo"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "About Me"
  url = "/tags/about/"
  weight = 100

[[menu.main]]
  name = "Life"
  url = "/categories/Life/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95